### ISSUE TITLE
versioning scheme for pypi

### ISSUE THREAD

**Issue by JensAc** [IENT/RDPlot#1]
We need to setup a versioning scheme according to
https://packaging.python.org/tutorials/distributing-packages/#choosing-a-versioning-scheme
in order to deploy the tool via pypi.
Sadly we cannot include the commit hash for the official package. 
Another opportunity would be to build packages for packagemanagers like apt or packman, but this would require maintenance for different packagemanagers.

**Comment by nolyn** [comment]
können sowas wie

1.2.0.dev1

nehmen und einen development branch haben der dann automatisch läuft und
master/stable nur wenn wir es manuell taggen/mergen.

ich kann bestimmt leicht ein skript bauen das die aktuelle pip version
prüft und darauf +1 macht. brauchen wir 3 zahlen oder reichen uns 2?

**Comment by JensAc** [comment]
I have solved it with only deploying tags on pypi and use just the current tag as version number. Please try
