### ISSUE TITLE
Dragging & Dropping in windows release 1.2.1 

### ISSUE THREAD

**Issue by emphos1** [IENT/RDPlot#26]
Currently, it's not possible to import log files/folders by dragging and dropping them. I have attached a sample encoder-log folder for debugging purposes.

[colmap_withoutRD_intact_delaunay2.zip](https://github.com/IENT/RDPlot/files/2459571/colmap_withoutRD_intact_delaunay2.zip)

**Comment by aachenmax** [comment]
This issue will be fixed with pull request #29
