### ISSUE TITLE
Warn user if comparing sequences with different number of QP or different QP values 

### ISSUE THREAD

**Issue by nolyn** [IENT/RDPlot#3]
see the attached logs as an example. 
for example sim1 has qp 22, 27, 32, 37, sim2 has qp 22, 24, 27, 29, 32, 34, 37. selecting them all does not make sense. a warning should be shown. same if sim1 has qp 22, 27, 32, 37, sim2 has qp 24, 29, 34, 39 (same number but different values)

[AerialCity_sim2.zip](https://github.com/IENT/RDPlot/files/1251228/AerialCity_sim2.zip)
[AerialCity_sim1.zip](https://github.com/IENT/RDPlot/files/1251229/AerialCity_sim1.zip)

**Comment by JensAc** [comment]
I think that was solved by 2a9987de89c66eeded778efbece370425f9deebf  in the meantime.
