### ISSUE TITLE
Export figure as TikZpicture seems to be broken in flatpak 

### ISSUE THREAD

**Issue by JensAc** [IENT/RDPlot#30]
The feature seems not to be working when RDPlot is installed via flatpak. However, it works perfectly fine, when running from source. Maybe there is some dependency missing in the package?

**Comment by nolyn** [comment]
this works for me, using version  1.3.1
at least when accessing normal user paths. 
when saving to /tmp for example it only works, when the specified name already includes .tex. when it doesn't work, it doesn't stall. just no file is created.

**Comment by JensAc** [comment]
Could it be a problem related to nfs?

**Comment by nolyn** [comment]
i think i also had the problem when trying to save to the local HD on Ubuntu 18.04.

**Comment by JensAc** [comment]
I will close that. Flatpak is of minor importance due pipx.
