### ISSUE TITLE
BD - Wrong average values when some results are missing

### ISSUE THREAD

**Issue by nolyn** [IENT/RDPlot#31]
When looking  at the bjontegaard table the average value calculation is wrong when results for some sequences are missing. This is espcecially confusing when two columns are complete. Their averages will still be wrong if something is missing in a third column. 

It is not sufficient to make the average correct for each column, this would make the averages not comparable when one column has more valid entries than another.

Possible fix: When some result is missing, delete the sequence (row) for all other opened  configurations as well.

**Comment by JensAc** [comment]
Actually, I am not sure, whether this can be addressed correctly. If I am not mistaken, missing BD-measurements are not included in the calculation of average values. 

If one column (i.e. coding configuration) has more entries than another one, IMHO the average values are not comparable in any case, or am I missing something here?

**Comment by JensAc** [comment]
This issue seems to be inactive for quite a while now. Therefore, I will close this.
