### ISSUE TITLE
Download for Mac

### ISSUE THREAD

**Issue by mertmerci** [IENT/RDPlot#34]
Hello,

I could not download the application to my Mac. Could you please describe the substeps more briefly, or maybe upload a video or documentation? 

Thank you for your time and kind interest.

**Comment by JensAc** [comment]
Hi, 
we do not ship applications for OSX directly. Did you try and follow the instructions in our README.md? If yes, could you give more detailed insights on what you have done and what failed exactly?

**Comment by mertmerci** [comment]
Hello again,

First of all, thank you for your quick and kind response. 

I faced with some issues but I think I solved them mainly, but to be on the same page let me share them with you.

At first, I see the errors below while downloading the packages under requirement.txt.

<img width="568" alt="Screenshot 2020-05-31 at 15 02 15" src="https://user-images.githubusercontent.com/44507442/83352658-ccb23480-a355-11ea-94fb-1d4ab9c2060e.png">

Then I update to pyqt5 and then I rerun the command and see the following result.

<img width="1094" alt="Screenshot 2020-05-31 at 15 43 11" src="https://user-images.githubusercontent.com/44507442/83352674-f703f200-a355-11ea-9eb3-ddb8c3e11df3.png">

Finally, I managed to build the app but I have the following issue right now. 

<img width="423" alt="Screenshot 2020-05-31 at 15 42 35" src="https://user-images.githubusercontent.com/44507442/83352690-169b1a80-a356-11ea-95cd-493a0f7dfc4e.png">

How should I proceed to handle this problem?
 
Thank you for your time and interest.

**Comment by JensAc** [comment]
It seems that you are using anaconda and this python distribution is not detected correctly by OSX. Actually, I do not have much experience with python on Mac and I do not own one for testing. Therefore, the easiest thing to do would be to follow the instructions under "Running from repository without installation". If you launch RDPlot from your "base" environment and all requirements are satisfied, you should end up with the tool starting.

**Comment by mertmerci** [comment]
Hello again,

I started to run it by the instructions "Running from the repository without installation". The result is presented below. 

<img width="569" alt="Screenshot 2020-06-01 at 13 13 53" src="https://user-images.githubusercontent.com/44507442/83399427-e0b76e00-a409-11ea-8847-4bdfaa9b2a1f.png">

The error is "no module named 'rdplot' ".

How could I download it or proceed?

**Comment by JensAc** [comment]
Please try and set the `PYTHONPATH` environment variable as well and report back whether that helped or not.

**Comment by mertmerci** [comment]
I tried to set the `PYTHONPATH` environment variable as it's explained on the tutorial in the following page: https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html

I opened the bash_profile.

<img width="571" alt="Screenshot 2020-06-04 at 16 04 00" src="https://user-images.githubusercontent.com/44507442/83760542-c38ad580-a67d-11ea-83f1-372e62d54679.png">

Added the path to the bottom.

<img width="824" alt="Screenshot 2020-06-04 at 16 04 20" src="https://user-images.githubusercontent.com/44507442/83760603-d7ced280-a67d-11ea-94a1-c46e571f39e6.png">

But it still does not work. 

<img width="497" alt="Screenshot 2020-06-04 at 16 07 40" src="https://user-images.githubusercontent.com/44507442/83760669-ecab6600-a67d-11ea-8233-0a5bcf9e8c71.png">

<img width="570" alt="Screenshot 2020-06-04 at 16 12 26" src="https://user-images.githubusercontent.com/44507442/83760863-3431f200-a67e-11ea-9383-f5265d421028.png">

**Comment by JensAc** [comment]
Actually, the `PATH` variable is not the same as the `PYTHONPATH` variable. So I think the editing in your bash.profile is not necessary. However, as your shell says it does not know the command `python3`. This depends on how python is installed. So please try and replace `python3` by `python`. Of course, your python executable from anaconda should be python3.

**Comment by mertmerci** [comment]
I undo the edit I did on bash.profile because after the edit the terminal started to work inconsistently. So, I'm still on the same problem which is " No module called 'rdplot' ".

**Comment by JensAc** [comment]
Ok. I think, I need more information on that. There are two different issues:

- The `No module called rdplot` error stems from a erroneous `PYTHONPATH`. 
- IMHO you somehow messed up your python installation, as your bash is reporting: 
`python3: command not found`

I guess, this has nothing to do with RDPlot. Therefore, I recommend the following steps:
1. Make sure that you can execute `python3` and end up in a python3 repl. 
2. Execute `PYTHONPATH=~/Desktop/RD_Dir/RDPlot/src/ python3 ~/Desktop/RD_Dir/RDPlot/src/rdplot/__main__.py`
3. Paste the output here, when it is not working

**Comment by mertmerci** [comment]
With this command, it started to work !! Thank you so much for your kind interest and patience, it really helped me a lot !!

**Comment by JensAc** [comment]
You are welcome. I will close this for now.
