### ISSUE TITLE
UI freezing when open logs multiple times

### ISSUE THREAD

**Issue by nolyn** [IENT/RDPlot#44]
Using menu -> Open file (RD-Data or log) and selecting many xml files, than doing the same again, with the same files causes RDPlot to freeze up. 

Drag&Drop for a directory multiple times works fine.

Tested on windows, using the installer.

**Comment by JensAc** [comment]
I cannot reproduce this on Linux. I guess some debugging on windows is required here, as it might be related to the platform specific representation of paths. Would it be possible that you provide more detailed information?

**Comment by JensAc** [comment]
Update: I also tested on Windows now, and I am still not able to reproduce this. Therefore, I will close this issue for now.
